### ISSUE TITLE
Replace instant query to range query(/loki/api/v1/query to /loki/api/v1/query_range)

### ISSUE THREAD

**Issue by arukiidou** [grafana/oats#48]
### test failed 
- https://github.com/grafana/docker-otel-lgtm/pull/109

```
  logQL query {service_name="rolldice"} |~ `Anonymous player is rolling the dice.*` response log queries are not supported as an instant query type, please change your query to a range query type err=<nil>

  [FAILED] in [It] - /home/runner/work/docker-otel-lgtm/docker-otel-lgtm/oats/yaml/runner.go:186 @ 09/19/24 20:18:18.007
  << Timeline

  [FAILED] Timed out after 300.000s.
  calling application for 5m0s should cause telemetry to appear
  The function passed to Eventually failed at /home/runner/work/docker-otel-lgtm/docker-otel-lgtm/oats/yaml/logs.go:15 with:
  Expected
      <string>: log queries are not supported as an instant query type, please change your query to a range query type
  to contain substring
      <string>: Anonymous player is rolling the dice
  In [It] at: /home/runner/work/docker-otel-lgtm/docker-otel-lgtm/oats/yaml/runner.go:186 @ 09/19/24 20:18:18.007
```

### what happned?

- https://grafana.com/docs/loki/latest/release-notes/v3-2/#upgrade-considerations
  - see docs: 
    - https://grafana.com/docs/loki/latest/reference/loki-http-api/#query-logs-at-a-single-point-in-time
    - https://grafana.com/docs/loki/latest/reference/loki-http-api/#query-logs-within-a-range-of-time

```
Fail log queries when executed on instant query endpoint
```

### how to fix?

https://github.com/grafana/oats/blob/9a79819efcde37f025613914708dd1ba721e5ddc/testhelpers/compose/local_compose_endpoint.go#L197

- Replace [/loki/api/v1/query](https://grafana.com/docs/loki/latest/reference/loki-http-api/#query-logs-at-a-single-point-in-time) to [/loki/api/v1/query_range](https://grafana.com/docs/loki/latest/reference/loki-http-api/#query-logs-within-a-range-of-time)

**Comment by zeitlinger** [comment]
fixed in https://github.com/grafana/oats/pull/46
